exclude_paths:
- "checkstyle/**"
- "coverage/**"
- "dist/**/*"
- "dist/reach.js"
- "dist/reach-debug.js"

ratings:
  paths:
  - "src/**.js"
  - "test/**.js"

engines:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.yml
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
